package nl.ordina.github.team

import kotlinx.serialization.Serializable
import nl.ordina.github.repository.*

@Suppress("PropertyName")
@Serializable
data class GitHubTeamRepository(
    val id: Int,
    val node_id: String,
    val name: String,
    val full_name: String,
    val owner: GitHubRepositoryOwner? = null,
    val private: Boolean,
    val html_url: String,
    val description: String? = null,
    val fork: Boolean,
    val url: String,
    val archive_url: String,
    val assignees_url: String,
    val blobs_url: String,
    val branches_url: String,
    val collaborators_url: String,
    val comments_url: String,
    val commits_url: String,
    val compare_url: String,
    val contents_url: String,
    val contributors_url: String,
    val deployments_url: String,
    val downloads_url: String,
    val events_url: String,
    val forks_url: String,
    val git_commits_url: String,
    val git_refs_url: String,
    val git_tags_url: String,
    val git_url: String? = null,
    val issue_comment_url: String,
    val issue_events_url: String,
    val issues_url: String,
    val keys_url: String,
    val labels_url: String,
    val languages_url: String,
    val merges_url: String,
    val milestones_url: String,
    val notifications_url: String,
    val pulls_url: String,
    val releases_url: String,
    val ssh_url: String,
    val stargazers_url: String,
    val statuses_url: String,
    val subscribers_url: String,
    val subscription_url: String,
    val tags_url: String,
    val teams_url: String,
    val trees_url: String,
    val clone_url: String? = null,
    val mirror_url: String? = null,
    val hooks_url: String,
    val svn_url: String? = null,
    val homepage: String? = null,
    val language: String? = null,
    val forks_count: Int? = null,
    val stargazers_count: Int? = null,
    val watchers_count: Int? = null,
    val size: Int? = null,
    val default_branch: String? = null,
    val open_issues_count: Int? = null,
    val is_template: Boolean? = null,
    val topics: List<String> = emptyList(),
    val has_issues: Boolean? = null,
    val has_projects: Boolean? = null,
    val has_wiki: Boolean? = null,
    val has_pages: Boolean? = null,
    val has_downloads: Boolean? = null,
    val has_discussions: Boolean? = null,
    val archived: Boolean? = null,
    val disabled: Boolean? = null,
    val visibility: String? = null,
    val pushed_at: String? = null,
    val created_at: String? = null,
    val updated_at: String? = null,
    val permissions: GitHubRepositoryPermissions? = null,
    val role_name: String? = null,
    val temp_clone_token: String? = null,
    val delete_branch_on_merge: Boolean? = null,
    val subscribers_count: Int? = null,
    val network_count: Int? = null,
    val code_of_conduct: GitHubRepositoryCodeOfConduct? = null,
    val license: GitHubRepositoryLicense? = null,
    val forks: Int? = null,
    val open_issues: Int? = null,
    val watchers: Int? = null,
    val allow_forking: Boolean? = null,
    val web_commit_signoff_required: Boolean? = null,
    val security_and_analysis: GitHubRepositorySecurityAndAnalysis? = null
)